version: '2'

services:
  pytest:
    build:
      context: .
      dockerfile: Dockerfile
    image: repoduce_pytest_mock_issue_84
    working_dir: /home/pi/dev/bossjones-github/repoduce_pytest_mock_issue_84
    environment:
      SERVER_LOG_MINIMAL: 1
      SERVER_APP_NAME: repoduce_pytest_mock_issue_84
      S6_KILL_FINISH_MAXTIME: 1
      S6_KILL_GRACETIME: 1
      SERVER_WORKER_PROCESSES: 1
      PYTHONUNBUFFERED: 1
    stdin_open: true
    tty: true
    entrypoint:
      - "/docker_entrypoint.sh"
      - "/bin/bash"
    volumes:
      - ./:/home/pi/dev/bossjones-github/repoduce_pytest_mock_issue_84:rw